# Generated by Django 4.2.7 on 2026-06-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(default='Основной зал', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tables',
                'ordering': ['number'],
            },
        ),
    ]
